### ISSUE TITLE
Practica interfaz

### ISSUE THREAD

**Issue by bg55-a** [SistemasTecTlaxiaco/practica-de-interfaz-grafica-en-visual-sutdio-app-prototipoxd#2]
[interfaz grafica calculadora.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-interfaz-grafica-en-visual-sutdio-app-prototipoxd/files/8090843/interfaz.grafica.calculadora.pdf)

**Comment by josealfredo79** [comment]
Falta la calificación

**Comment by josealfredo79** [comment]
Nuevamente falta la calificacion

**Comment by josealfredo79** [comment]
Nuevamente pido la calificacion

**Comment by josealfredo79** [comment]
Suplico...ruego...de plano...aquí debe ir la calificación

**Comment by EvelynLopezz** [comment]
Calificación 19

**Comment by josealfredo79** [comment]
Bien hecho y revisado
